config/routes.rb
Rails.application.routes.draw do

  root to: 'transactions#index'
  resources :transactions, only: [:show, :index]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  searchkick locations: [:location]

  def address
    [street, city, zip, state].compact.join(", ")
  end

  def address_changed?
    street_changed? |  city_changed? |  zip_changed? |  state_changed?
  end

  def search_data
    attributes.merge location: {lat: latitude, lon: longitude}
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  before_action :set_user, only: [:show]

  def index
    per_page = 10
    @transactions = if params[:l]
                        sw_lat, sw_lng, ne_lat, ne_lng = params[:l].split(",")
                        #center = Geocoder::Calculations.geographic_center([[sw_lat, sw_lng], [ne_lat, ne_lng]])
                        #distance = Geocoder::Calculations.distance_between(center, [sw_lat, sw_lng])
                        #box = Geocoder::Calculations.bounding_box(center, distance)
                        #Transaction.within_bounding_box(box)

                        Transaction.search('*',page: params[:page], per_page: per_page, where: {
                          location: {
                            top_left: {
                              lat: ne_lat, 
                              lon: sw_lng,
                              }, 
                            bottom_right: {
                              lat: sw_lat, 
                              lon: ne_lng,
                              }
                            }
                        })
                      elsif params[:near]
                        # Transaction.near(params[:near]).per(per_page)
                        location = Geocoder.search(params[:near]).first
                        Transaction.search('*',page: params[:page], per_page: per_page,
                         boost_by_distance: {
                           location: {
                             origin: {
                               lat: location.latitude, 
                               lon: location.longitude
                              }
                            }
                          },
                         where: {
                          location: {
                            near: {
                              lat: location.latitude, 
                              lon: location.longitude
                              }, 
                            within: "50mi"
                          }
                        })
                      else
                        Transaction.all.page(params[:page]).per(per_page)
                      end
  end

  def show
  end

  private

  def set_user
    id = params[:id]
    @transaction = Transaction.find(id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeolocationAndSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://maps.googleapis.com/maps/api/js?key=<%=Figaro.env.gmaps_key%>" async defer></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  
</html>

app/views/transactions/_list.html.erb
<%=tag.div id: 'transaction_list', data: {transactions: @transactions.to_json(methods: [:address]), l: params[:l]} do %>
  <%= paginate @transactions, remote: true %>
  <hr>
  <%= render @transactions %>  
<%end%>

app/views/transactions/_transaction.html.erb
<div>
  <% @transactions.each do |tr| %>
    <h3><%= link_to "LINK: #{tr.id}", transaction_path(tr) %></h3>
    <p> adrress: <%= tr.address %></p>
    <p> price: <%= tr.price %></p>
  <% end %>
</div>
<hr>

app/views/transactions/index.html.erb
<h1>Transaction list </h1>
<%= form_with(url: transactions_path, local: true, method: :get) do |f| %>
  <%= f.text_field :near, placeholder: "search" %>
  <%= f.submit %>
<% end  %>
<div class="container"> 
  <div>
    <%= render partial: 'list'%>
  </div>
  <div>
    <%= tag.div nil, id: "map" %>
  </div>
</div>

app/views/transactions/index.js.erb
$('#transaction_list').replaceWith("<%= j render partial: "list"%>")
addMarkers()

app/views/transactions/show.html.erb
<h1>Transaction id: <%= @transaction.id %></h1>
<hr>
<h3>
    <%= link_to "LINK: #{@transaction.id}", transaction_path(@transaction) %>
</h3>
<p> adrress: <%= @transaction.address %></p>
<p> price: <%= @transaction.price %></p>

<%= link_to 'listing', root_path %>